baseURL = 'https://sudhanshusingh-me.netlify.app/'
languageCode = 'en-us'
title = 'Sudhanshu Singh'
theme = 'PaperMod'


[params]

    [params.homeInfoParams]
        Title = "ğŸš€ Full-Stack Developer  | Tech Enthusiast"
    Content = """ 
    ğŸ‘‹ Hey there! I'm Sudhanshu Singh, a passionate Full-Stack Developer dedicated to crafting seamless digital experiences.  

    ğŸ”¥ What I Do:  
    - ğŸ’» Build scalable & user-friendly web applications.  
    - ğŸ“Š Explore Data Analytics, UX Design, AI/ML to enhance decision-making.  
    - ğŸš€ Stay updated with the latest tech trends to deliver cutting-edge solutions.  

    ğŸ¤ Let's Collaborate!  
    - Open to exciting projects, freelance opportunities, and tech discussions.

    ğŸ“Œ Fun Fact: I love solving complex problems and turning ideas into reality!  
    """
    [[params.socialIcons]]
        name = 'github'
        url = 'https://github.com/sudhanshusingh-g'
    [[params.socialIcons]]
        name = 'linkedin'
        url = 'https://www.linkedin.com/in/sudhanshusingh32/'
    [[params.socialIcons]]
        name = 'twitter'
        url = 'https://x.com/SinghSudha78033'
    [[params.socialIcons]]
        name = 'email'
        url = 'mailto:sudsingh32@gmail.com'

    showBreadCrumbs = true
    showReadingTime = true
    showPostNavLinks = true
    showShareButtons = true

[menu]

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10


  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "https://docs.google.com/document/d/1PJJ-WvtcVJywbtSaK9WH0fXAMlap95BpP95vNhFPhgo/edit?usp=sharing"
    weight = 20
    pre = "<i class='fas fa-file-alt'></i>"
